/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#40000c',
        'on-primary-fixed-variant': '#3f465c',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#920028',
        'primary-fixed': '#dae2fd',
        'inverse-primary': '#bec6e0',
        secondary: '#ba0035',
        'on-error-container': '#93000a',
        'on-secondary-container': '#fffbff',
        'tertiary-container': '#0b1c30',
        background: '#f7f9fb',
        'secondary-fixed': '#ffdada',
        'secondary-fixed-dim': '#ffb3b6',
        'secondary-container': '#e21e49',
        'inverse-surface': '#2d3133',
        'on-primary-fixed': '#131b2e',
        'surface-tint': '#565e74',
        'on-tertiary-fixed': '#0b1c30',
        tertiary: '#000000',
        'on-error': '#ffffff',
        'on-surface': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed-dim': '#bec6e0',
        'tertiary-fixed-dim': '#b7c8e1',
        outline: '#76777d',
        primary: '#000000',
        'surface-dim': '#d8dadc',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#75859d',
        'surface-container-high': '#e6e8ea',
        'on-secondary': '#ffffff',
        'on-primary-container': '#7c839b',
        'primary-container': '#131b2e',
        'surface-container': '#eceef0',
        'on-background': '#191c1e',
        'outline-variant': '#c6c6cd',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#d3e4fe',
        'on-tertiary-fixed-variant': '#38485d',
        'surface-variant': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'surface-container-low': '#f2f4f6',
        'on-surface-variant': '#45464d',
        surface: '#f7f9fb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['IBM Plex Sans', 'sans-serif'],
        'headline-md': ['IBM Plex Sans', 'sans-serif'],
        'headline-lg': ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
