/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#002113',
        'on-primary-fixed-variant': '#3f465c',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#005236',
        'primary-fixed': '#dae2fd',
        'inverse-primary': '#bec6e0',
        secondary: '#006c49',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714d',
        'tertiary-container': '#0d1c2e',
        background: '#f7f9fb',
        'secondary-fixed': '#6ffbbe',
        'inverse-surface': '#2d3133',
        'on-primary-fixed': '#131b2e',
        'surface-tint': '#565e74',
        'on-tertiary-fixed': '#0d1c2e',
        tertiary: '#000000',
        'on-error': '#ffffff',
        'on-surface': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed-dim': '#bec6e0',
        'tertiary-fixed-dim': '#b9c7df',
        outline: '#76777d',
        primary: '#000000',
        'surface-dim': '#d8dadc',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#77859a',
        'surface-container-high': '#e6e8ea',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#45464d',
        'primary-container': '#131b2e',
        'surface-container': '#eceef0',
        'secondary-fixed-dim': '#4edea3',
        'on-background': '#191c1e',
        'outline-variant': '#c6c6cd',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#d5e3fc',
        'on-tertiary-fixed-variant': '#3a485b',
        'surface-variant': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'on-primary-container': '#7c839b',
        'secondary-container': '#6cf8bb',
        'surface-container-low': '#f2f4f6',
        surface: '#f7f9fb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
